version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nt
      POSTGRES_USER: nt
      POSTGRES_PASSWORD: nt
    volumes:
      - "db:/var/lib/postgresql/data/"

volumes:
  db:
