version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: te
      POSTGRES_USER: te
      POSTGRES_PASSWORD: te
    volumes:
      - "db:/var/lib/postgresql/data/"

volumes:
  db:
