POST https://django-notion.herokuapp.com/api/token/
Content-Type: application/json

{"email": "karim.valeev.i@gmail.com", "password": "no.tion.2021"}

###
GET https://django-notion.herokuapp.com/notes/
Accept: application/json
Authorization: Bearer token...

###
POST https://django-notion.herokuapp.com/notes/
Content-Type: application/json
Authorization: Bearer

{
  "topic":"Проверочная заметка",
  "body":"Описание проверочной записки",
  "parent":""
}


###
PUT http://127.0.0.1:8000/notes/8/
Content-Type: application/json
Authorization: Bearer

{
  "topic":"Проверочная заметка 8"
}


###
DELETE http://127.0.0.1:8000/notes/8/
Authorization: Bearer

###
