POST http://127.0.0.1:8000/api/1.0.0/token/
Content-Type: application/json

{"email": "karim.valeev.i@gmail.com", "password": "admin"}

###
GET http://127.0.0.1:8000/api/1.0.0/notes/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjM4NDQyOTcxLCJqdGkiOiI5YmEyMmVkZDU3YjU0MjAwOGNmMmMxZjU2MjgzYTc2MiIsInVzZXJfaWQiOjF9.MBM-If1nXBw35sU48JfZPpi0NByBH45vDB1mPfOepvI

###
POST https://django-notion.herokuapp.com/notes/
Content-Type: application/json
Authorization: Bearer

{
  "topic":"Проверочная заметка",
  "body":"Описание проверочной записки",
  "parent":""
}


###
PUT http://127.0.0.1:8000/notes/8/
Content-Type: application/json
Authorization: Bearer

{
  "topic":"Проверочная заметка 8"
}


###
DELETE http://127.0.0.1:8000/notes/8/
Authorization: Bearer

###
