# Generated by Django 3.2.9 on 2021-11-16 03:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_note_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="url",
            field=models.URLField(max_length=500, verbose_name="URL"),
        ),
    ]
