# Generated by Django 3.2.9 on 2021-11-16 19:12
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_note_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user", verbose_name="Author"),
        ),
    ]
